# Site
name: 'صحيفة طلاب قريش'
description: 'صحيفة طلاب قريش'
logo: 'assets/images/logo.jpeg'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'ba3oos-ml'
email: ''
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    hamza:
      name:           حمزة مرزوق
      site:           لا يوجد موقع الكتروني
      avatar:         assets/images/gentle.jpg
      bio:            طالب شعبة 203، مؤسس موقع صحيفة طلاب قريش وأحد الكُتّاب في الموقع
      email:          ايميل محظور
      twitter:        https://twitter.com/JustBalmier
    abdul:
      name:           عبدالإله الحايك
      site:           لا يوجد موقع الكتروني
      avatar:         assets/images/abdul.jpeg
      bio:            طالب شعبة 202 وأحد الكُتّاب في موقع صحيفة طلاب قريش
      email:          ايميل محظور
      twitter:        تويتر محظور
    rami:
      name:           رامي المارديني
      site:           لا يوجد موقع الكتروني
      avatar:         assets/images/rami.jpg
      bio:            طالب شعبة 204 وأحد الكُتّاب في موقع صحيفة طلاب قريش
      email:          ايميل محظور
      twitter:        تويتر محظور
#     yasser:
#       name:           ياسر السعيد
#       site:           لا يوجد موقع الكتروني
#       avatar:         assets/images/av3.png
#       bio:            طالب شعبة 204 وأحد الكُتّاب في موقع صحيفة طلاب قريش
#       email:          ايميل محظور
#       twitter:        تويتر محظور

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: hamza
      avatar: assets/images/gentle.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
